---
title: "Research"
output:
  html_document:
    css: style.css
---

<style>
body {
text-align: justify}
</style>

## Working papers

[Incomplete Peace: Unintended Consequences of Partial Conflict Resolution in Multilateral Conflicts](http://publish.illinois.edu/fceballoss/files/2020/11/JMC_FCeballosS.pdf). **Job Market Paper**

This paper provides evidence on the impact of conflict resolution processes (CRPs) in settings of multilateral conflict. Previous studies on CRPs have focused on bilateral conflicts between the State and a single armed group, finding positive impacts on economic activity after the demobilization of the armed group, a phenomenon known as the peace dividend. This paper studies the case where the State is warring multiple armed groups and a peace agreement is reached with only one of them. I find that the impact of a CRP in this setting is heterogeneous: areas where the sole armed group demobilized, experience an increase in economic activity; while areas where the demobilizing group was outlived by another armed group experience no change in economic activity and a surge in illegal economic activity in the form of coca production.

[The Effect of Climate Variability on Colombian Coffee Productivity: a Dynamic Panel Model Approach](http://publish.illinois.edu/fceballoss/files/2020/11/CChange2_AgrSys.pdf). With Sandy Dall'erba. Invited to revise and resubmit. Agricultural Systems

Coffee is one of the trademarks of Colombia. Currently, up to a half million Colombian families depend directly on coffee production for their livelihoods. As such, there has been increasing concerns about how coffee productivity will react to changing climate conditions and how coffee growers could adapt their production practices. This paper is one of the first to estimate the production function of Colombian coffee at the municipal level and to make projections about its future productivity. Using a panel data set measured across municipalities over 2007-2013, we find that productivity depends on altitude as well as on March temperature and precipitation. We estimate projections based on the 2.6, 4.5, and 6.0 Representative Concentration Pathways derived from Global Circulation Models to find out that productivity over 2041-2060 is expected to increase by 7.6% on average. However, we find that this forecast varies greatly according to altitude. Indeed, municipalities above median elevation will increase their productivity by 16%, while those below the median will experience a 8.1% decrease in productivity. This result implies that place-tailored strategies for coffee production in Colombia are required to adapt to changing climate conditions in the future.

[Technology Diffusion Through Vocational Training of High School Students: Experimental Evidence from Nicaragua](http://publish.illinois.edu/fceballoss/files/2020/11/Fabretto_Ag_Sys.pdf). Under review. Journal of Agricultural Education and Extension. With Mary Arends-Kuenning and Anina Hewey

Farmers’ adoption of new agricultural technologies is a risky endeavor that requires reliable and persuasive information, clarity about the technology’s suitability to local conditions, and careful instruction to be successful. Often, these standards are not met in developing countries due to the scarcity of local research facilities; and the sparse network of extension agents. Different forms of social learning have been explored to bridge the latter issue, often acting as complements to conventional extension services. This paper explores one such program, the Tutorial Learning System (SATec) implemented by the Fabretto Foundation, which provides vocational training to high school students in rural Nicaragua. We conduct a randomized control trial in nine communities and evaluate changes in the knowledge of agricultural technologies, access to credit markets, and technology adoption for parents and students. Our results show improvements in knowledge-based outcomes for students and parents, and increased access to credit markets and adoption of agricultural technologies by parents. Given the increase in schooling across developing countries, our positive results suggest promising returns to programs designed around within-family technology diffusion that can complement more conventional forms of agricultural extension.



